### PR TITLE
modified profile section

### PR DESCRIPTION
**Pull request by rkishan516**
Modified Profile Section In Profile Setting Section

### CODE REVIEW

**Comment by anuragteapot** [comment]
Always add some screenshots of your changes good practice.

**Comment by rkishan516** [comment]
screenshot from 2018-12-07 14-12-32
screenshot from 2018-12-07 14-12-35
screenshot from 2018-12-07 14-12-41

**Comment by anuragteapot** [comment]
Hmm, I think the previous one is pretty good. The information you were showing along with profile image is making the image messy. You can this information below profile image. It great if we have nice and clean UI. It's my opinion.

**Comment by rkishan516** [comment]
Ok, I will try to Change it with new One

**Pull request closed without merging**
