### PR TITLE
Updated HolidayList For Year 2019

### LINKED ISSUE #27: HolidayList is Not Up-to-Date for 2019
HolidayList is for 2018 Update it for 2019

### PR DESCRIPTION
**Pull request by rkishan516**
Fixes #27 
Updated Holiday List

### CODE REVIEW

**Comment by rkishan516** [comment]
@Anu1601CS Please look at these PR's

**Comment by rkishan516** [comment]
@Anu1601CS Please look all these PR's ASAP.

**Comment by rkishan516** [comment]
@Anu1601CS Please look all these PR's ASAP.

**Review by anuragteapot — APPROVED** [review]
Good Work

**Pull request merged**
